### ISSUE TITLE
Pipeline hits error and ends early

### ISSUE THREAD

**Issue by erikwaskiewicz** [AWGL/cruk_pipeline#9]
Hits error during TST170 kickoff:
```
Traceback (most recent call last):
  File "cruk_smp.py", line 218, in <module>
    cr.main()
  File "cruk_smp.py", line 141, in main
    tst_170 = launch_tst.launch_tst170(sample_pairs)
  File "/share/data/results/-----/SMP2v3/launch_app.py", line 42, in launch_tst170
    tst_170_launch = self.launch_tst170_analysis(dna_sample)
  File "/share/data/results/-----/SMP2v3/launch_app.py", line 66, in launch_tst170_analysis
    rna_biosample_id = self.get_biosamples(f"{self.worksheet}-{rna_sample}")
  File "/share/data/results/-----/SMP2v3/launch_app.py", line 171, in get_biosamples
    raise Exception(f"No biosample with name {biosample_name} in project {self.project_id}")
Exception: No biosample with name ----- in project -----
```
Biosample names/ project IDs are in real traceback, removed from here just in case.

**Comment by erikwaskiewicz** [comment]
Some TST170 apps were kicked off successfully. Looking at the missing sample, it has been uploaded but the timestamp is just after the other TST170 apps were kicked off, so we probably just need a time delay after the last FASTQ upload so basespace has time to catch up with itself.
